export const GAME_EVENTS = {
    STATE_CHANGED: 'game-state-changed',
    ENEMY_SPAWNED: 'enemy-spawned',
    ENEMY_REMOVED: 'enemy-removed',
    ENEMY_SELECTED: 'enemy-selected',
    ENEMY_DAMAGED: 'enemy-damaged',
    ENEMY_ATTACKED: 'enemy-attacked',
    TOWER_PLACED: 'tower-placed',
    TOWER_REMOVED: 'tower-removed',
    TOWER_SELECTED: 'tower-selected',
    TOWER_ATTACKED: 'tower-attacked',
    TOWER_DAMAGED: 'tower-damaged',
    SELECTION_CHANGED: 'selection-changed',
    SELECTION_CLEARED: 'selection-cleared',
    START_WAVE: 'start-wave',
    WAVE_COMPLETED: 'wave-completed',
    PICK_WAVE_UPGRADE: 'pick-wave-upgrade',
    REQUEST_INVENTORY: 'request-inventory',
    INVENTORY_SNAPSHOT: 'inventory-snapshot',
    SCENE_READY: 'current-scene-ready',
} as const;
